config/routes.rb
MyBlog::Application.routes.draw do

  match 'contact' => 'messages#new', :as => 'messages', :via => :get
  match 'contact' => 'messages#create', :as => 'messages', :via => :post

  root :to => 'pages#home'

  resources :articles do
    resources :comments
  end

  resources :tags
  resources :authors

  resources :author_sessions, only: [ :new, :create, :destroy ]

  match 'login' => 'author_sessions#new'
  match 'logout' => 'author_sessions#destroy'

  match "home", to: 'pages#home'

  match "portfolio", to: 'pages#portfolio'
  

end

app/models/article.rb
class Article < ActiveRecord::Base
  	attr_accessible :title, :body, :tag_list, :image
  	has_many :comments
  	has_many :taggings
  	has_many :tags, through: :taggings

    # part of paperclip. declares that this model can accept a file attachemnt
    has_attached_file :image

    validates_presence_of :title
    validates_presence_of :body

  	def tag_list
  		tags.join(", ")
  	end

  	def tag_list=(tags_string)
  		tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
  		new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by_name(name) }
  		self.tags = new_or_found_tags
  	end

      	
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	before_filter :require_login, except: [:index, :show]

	def index
		@articles = Article.all
	end

	def show
		@article = Article.find(params[:id])
		@comment = Comment.new
		@comment.article_id = @article.id
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(params[:article])
		if @article.save
			redirect_to article_path(@article)
		else
			redirect_to action: new
		end
	end

	def destroy
		@article = Article.find(params[:id]).destroy
		redirect_to action: "index"
	end

	def edit
		@article = Article.find(params[:id])
	end

	def update
		@article = Article.find(params[:id])
		if @article.update_attributes(params[:article])
			redirect_to article_path(@article)
		else
			redirect_to action: edit
		end
	end

end

app/helpers/articles_helper.rb
module ArticlesHelper

	def latest_article
      @article = Article.order("created_at").last()
    end

    def recent_articles
    	@articles = Article.order("created_at desc").limit(3)
    end
end

app/views/articles/_comment.html.erb
<div>
	<h5 class="comment"><%= comment.author_name %> - posted <%= distance_of_time_in_words(comment.article.created_at, comment.created_at) %> ago</h5>
	<!--<h6>Posted <%= distance_of_time_in_words(comment.article.created_at, comment.created_at) %></h6>-->
	<p class="comment"><%= comment.body %></p>
	<div>
	<ul>
		<% if logged_in? %>
			<%= link_to 'Delete Comment', article_comment_path(comment.article, comment), method: :delete, 
				confirm: "Delete the Comment?", :class => "admin" %>
		<% end %>
	</ul>
</div>

</div>

app/views/articles/_form.html.erb
<%= simple_form_for(@article, html: {multipart: true, class: "form-horizontal"}) do |f| %>
  <ul>
  <% @article.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <%= f.input :title, input_html: { class: 'span12', }  %>
  <%= f.input :body, input_html: { class: 'span12', }  %>
  <%= f.input :tag_list %>
  <p>
    <% if @article.image.exists? %>
      <%= image_tag @article.image.url %>
    <% end %>
    <%= f.input :image %>
  </p>
  <div class="form-actions">
    <button type="submit" class="btn btn-primary">Save changes</button>
  </div>
  <!--<div class="form-actions">
    <%= f.button :submit %>
  </div>-->
<% end %>

app/views/articles/edit.html.erb
<h2>Edit a Article</h2>

<%= render partial: 'form' %>

app/views/articles/index.html.erb
<h1>All Articles</h1>

<ul id="articles">
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title,  article_path(article) %>
      <br>
      <%= truncate(article.body, length: 230, separator: ' ') %> <%= link_to "Read More", article_path(article) %>
    </li>
  <% end %>
</ul>
<% if logged_in? %>
	<%= link_to "New Article", new_article_path, :class=> "admin" %>
<% end %>

app/views/articles/new.html.erb
<h2>Create a New Article</h2>

<%= render partial: 'form' %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<!--needs fixed to add the 'th' on days-->
<em><%= @article.created_at.strftime("%A, %B %-d, %Y") %></em>
<hr />
<div>
	<p>
	<% if @article.image.exists? %>
      <%= image_tag @article.image.url %>
    <% end %>
	</p>
</div>

<div>
	 <%= markdown @article.body %>
</div>
<br>
<div>
	<ul>
		<% if logged_in? %>
			<%= link_to '<< Back to Articles List', articles_path, :class => "admin" %> | 
			<%= link_to 'Delete', article_path(@article), method: :delete, confirm: "Delete the Article?", :class => "admin" %> | 
			<%= link_to 'Edit', edit_article_path(@article), :class => "admin" %>
		<% end %>
	</ul>
</div>
<div>
	<h4>Comments (<%= @article.comments.size %>)</h4>
	<%= render partial: 'articles/comment', collection: @article.comments %>
</div>
<div><%= render partial: 'comments/form' %></div>