config/routes.rb
MyBlog::Application.routes.draw do

  match 'contact' => 'messages#new', :as => 'messages', :via => :get
  match 'contact' => 'messages#create', :as => 'messages', :via => :post

  root :to => 'pages#home'

  resources :articles do
    resources :comments
  end

  resources :tags
  resources :authors

  resources :author_sessions, only: [ :new, :create, :destroy ]

  match 'login' => 'author_sessions#new'
  match 'logout' => 'author_sessions#destroy'

  match "home", to: 'pages#home'

  match "portfolio", to: 'pages#portfolio'
  

end

app/views/layouts/_navbar.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="navbar-inner">
      <div class="container-fluid">
        <nav>
          <ul class="nav pull-right">
            <% if logged_in? %>
              <li><%= link_to "Logout", logout_path %></li>
            <% end %>
          </ul>
          
        </nav>
      </div>
    </div>
  </header>

app/views/layouts/_sidebar.html.erb
<div class="span4">
  <div class="well sidebar-nav">
      <ul class="nav nav-list">
        <li class="nav-header">About Me</li>
          <em>This is some example text for the About me Section. I am just posting in some random text to get the layout done.</em>
              
        <li class="nav-header">Pages</li>
        <li><%= link_to "Home", home_path %></li>
        <li><%= link_to "Blog", articles_path %></li>
        <li><%= link_to "Portfolio", portfolio_path %></li>
        <li><%= link_to "Contact", messages_path %></li>
        <li class="nav-header">Recent Posts</li>
        <% recent_articles.each do |article| %>
          <li><%= link_to article.title, article_path(article) %></li>
        <% end %>
      </ul>
  </div><!--/.well -->
</div><!--/span-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!DOCTYPE html>
<html>
<head>
  <title>System Admin & Software Developer - Jason Shaffer</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>
<body>
	<%= render 'layouts/navbar' %>

	<!--sidebar-->
	<div class="container-fluid">
      <div class="row-fluid">
        <!--sidebar-->
        <%= render 'layouts/sidebar' %>
        <!--articles-->
        <div class="span8">
          <%= yield %>
        </div><!--/span-->           
      </div><!--/row-->
  </div><!--/container-->
  <hr>
  <h6>
    <% if logged_in? %>
      <%= "Logged in as #{current_user.username}" %>
    <% end %>
  </h6>
</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>System Admin & Software Developer - Jason Shaffer</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>
<body>
	<%= render 'layouts/navbar' %>

	
	<div class="container-fluid">
      <div class="row-fluid">
        <!--sidebar-->
        <%= render 'layouts/sidebar' %>
        <!--main banner-->
        <div class="span8">
          <div class="hero-unit">
			       <h1>My Name</h1>
        	   <p>This is the homepage, portfolio and blog. There will be some more random text here.</p>
          </div><!--/hero-->          
          <div class="row-fluid">
            <div class="span8">
              <%= yield %>
            </div><!--/span-->           
          </div><!--/row-->
        </div><!--/span-->
      </div><!--/row-->
  </div><!--/container-->
  <hr>
  <h6>
    <% if logged_in? %>
      <%= "Logged in as #{current_user.username}" %>
    <% end %>
  </h6>



</body>
</html>